// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfwgxiRwAO4soNhPBwkBESe_g05XDKpOQ',
    appId: '1:749831483154:web:3c414480740f615b6bcdcb',
    messagingSenderId: '749831483154',
    projectId: 'flutterfire-ui-codelab-14364',
    authDomain: 'flutterfire-ui-codelab-14364.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-14364.firebasestorage.app',
    measurementId: 'G-1WL92H4SLW',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDvK8N5lBPdm4bjBLmRmkaTmwRVKgPYNg',
    appId: '1:749831483154:android:9b01821ef7e608c16bcdcb',
    messagingSenderId: '749831483154',
    projectId: 'flutterfire-ui-codelab-14364',
    storageBucket: 'flutterfire-ui-codelab-14364.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6zEk05iFJju7gbaaYqNGoHSTeo7po-pY',
    appId: '1:749831483154:ios:7c5dad03a449ad986bcdcb',
    messagingSenderId: '749831483154',
    projectId: 'flutterfire-ui-codelab-14364',
    storageBucket: 'flutterfire-ui-codelab-14364.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6zEk05iFJju7gbaaYqNGoHSTeo7po-pY',
    appId: '1:749831483154:ios:7c5dad03a449ad986bcdcb',
    messagingSenderId: '749831483154',
    projectId: 'flutterfire-ui-codelab-14364',
    storageBucket: 'flutterfire-ui-codelab-14364.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

}